image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/viaduck/ci

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - lint
    - test
    - coverage

build:linux:x86_64:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -GNinja ../ -DGTEST_SRC_DIR=/usr/src/googletest/
        - ninja
    artifacts:
        expire_in: 2h
        paths:
        - build/

lint:linux:x86_64:
    stage: lint
    script:
        - vd-lint SecureMemory $PWD
    needs:
        - job: build:linux:x86_64
          artifacts: false

test:linux:x86_64:
    variables:
      GIT_STRATEGY: none
    stage: test
    script:
        - cd build
        - test/secure_memory_test
    needs:
        - build:linux:x86_64

coverage:linux:x86_64:
  stage: coverage
  script:
    - cd build
    - cmake . -DCMAKE_BUILD_TYPE=Debug -DVIADUCK_COVERAGE=ON
    - ninja secure_memory_test_coverage
  artifacts:
    paths:
      - build/secure_memory_test_coverage/
  needs:
    - build:linux:x86_64

