image: viaduck/ci

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - lint
    - test

build:linux:x86_64:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -GNinja ../ -DGTEST_SRC_DIR=/usr/src/googletest/
        - ninja
    artifacts:
        expire_in: 2h                   # do not pollute disk
        paths:
        - build/

lint:linux:x86_64:
    stage: lint
    script:
        - vd-lint SecureMemory $PWD
    needs:
        - job: build:linux:x86_64
          artifacts: false

test:linux:x86_64:
    variables:
      GIT_STRATEGY: none
    stage: test
    script:
        - cd build
        - test/SecureMemory_Test             # runs gtest target
    needs:
        - build:linux:x86_64

